[build]
base = "intakeflow-frontend"
command = "npm ci && npm run build"
publish = "dist"

[build.environment]
VITE_API_BASE = "https://intakeflow-api.onrender.com/api/Projects"
VITE_API_KEY = "dev-12345"
