[build]
  base    = "intakeflow-frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_BASE = "https://REPLACE_ME_AFTER_RENDER_DEPLOYS/api/Projects"
  VITE_API_KEY  = "dev-12345"
